---
services:
  solomon-arbor:
    image: squidfunk/mkdocs-material
    build:
      context: .
      dockerfile: Dockerfile
    hostname: solomon-arbor
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
    restart: always
