site_name: Solomon's Arboretum
site_url: https://solomon.cabecasa.net
theme:
  name: material
  font:
     text: Acme
     #text: Berkshire Swash
     #text: Amita
  logo: images/logo/sa-logo-1.jpg
  favicon: images/logo/sa-logo-1.jpg
  icon:
    annotation: material/arrow-right-circle
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    # test
    - navigation.indexes
    - navigation.sections
  language: en

  # Color Scheme for both light and dark theme
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: default 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode    
      primary: grey
      accent: lime

#extra:
#  generator: false
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences

# Extenstion for mermaid support
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins
plugins:
  # GLightBox - Photos
   - glightbox:
       touchNavigation: true
       loop: true
       effect: zoom
       slide_effect: fade
       width: 100%
       height: auto
       zoomable: false
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_themed: false
       auto_caption: true
       caption_position: bottom
       background: white
       shadow: true
       manual: false
extra:
  generator: false


# Navigation
nav:
  - Solomon's Arboretum: index.md
  - Athenaeum: 
    - athen/index.md
  - Exhibition:
    - exhibition/index.md
  - Scions of the Covenant:
    - sotc/index.md
    - The Shadow One and the Prisoner: sotc/shadow-prisoner.md
    - The Spec Ops and the Healer: sotc/specops-healer.md
    - The Convict and the Spy: sotc/convict-spy.md
    - The Witch and the Templar: sotc/witch-templar.md
  - Credits: credits.md