site_name: Solomon's Arboretum
site_url: https://gamefreakcabe.github.io/
theme:
  name: material
  font:
     #text: Acme
     text: Berkshire Swash
  logo: logo/sa-logo-1.jpg
  favicon: logo/sa-logo-1.jpg
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    # test
    - navigation.indexes
    - navigation.sections
  language: en

  # Color Scheme for both light and dark theme
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode    
      primary: black
      accent: lime

#extra:
#  generator: false
markdown_extensions:
  - attr_list
  - md_in_html

# Extenstion for mermaid support
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Navigation
nav:
  - Home: index.md
  - Athenaeum: 
    - athen/index.md
  - Scions of the Covenant:
    - sotc/index.md
    - The Shadow One and the General: sotc/shadow-prisoner.md
    - The Spec Ops and the Healer: sotc/specops-healer.md
    - The Convict and the Spy: sotc/convict-spy.md
  - Credits: credits.md